language: node_js
node_js:
  - "8"

before_script:
  - psql -U postgres -c 'create role app with LOGIN;'
  - psql -U postgres -c 'create database ample_test;'
  - psql -U postgres -d ample_test -c 'create extension postgis;'
  - ./node_modules/.bin/db-migrate up --env test

services:
  - postgresql

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

notifications:
  email:
    on_success: never
    on_failure: change
